### PR TITLE
End with new line was not being considered, it always defaulted to true....

### PR DESCRIPTION
**Pull request by petterfranzen**
... Also, a newline was applied even if the buffer already had one.

### CODE REVIEW

**Comment by petterfranzen** [comment]
Any update on this suggestion?

**Comment by vkadam** [comment]
Looked into it, test cases failed as its this change is not backward compatible, will you please make it as default to true and disable from config if required.

**Comment by petterfranzen** [comment]
Thanks for taking the time, when I run "grunt test" or "npm test" on master, as is, I still get 14/23 failed tests. Hence why I didn't spot that.
I will modify the commit to default to true like so:
-        addNewLine = beautifyConfig.end_with_newline;
+        addNewLine = beautifyConfig.end_with_newline === false ? false : true;

**Comment by vkadam** [comment]
Will get it fixed. Closing as duplicate of #45

**Comment by vkadam** [comment]
Pushed fix in version 0.2.9

**Pull request closed without merging**
